import 'package:url_launcher/url_launcher.dart';

class WhatsAppService {
  static Future<void> sendPrescription({
    required String phoneNumber,
    required String patientName,
    required String prescriptionText,
    String? doctorName,
  }) async {
    final message = _formatPrescription(patientName, prescriptionText, doctorName);
    final cleaned = _cleanPhone(phoneNumber);
    final encoded = Uri.encodeComponent(message);

    // Try WhatsApp app
    final waUri = Uri.parse('whatsapp://send?phone=$cleaned&text=$encoded');
    if (await canLaunchUrl(waUri)) {
      await launchUrl(waUri, mode: LaunchMode.externalApplication);
      return;
    }

    // Try wa.me (opens in browser if WhatsApp not installed)
    final webUri = Uri.parse('https://wa.me/$cleaned?text=$encoded');
    if (await canLaunchUrl(webUri)) {
      await launchUrl(webUri, mode: LaunchMode.externalApplication);
      return;
    }

    // Last resort: open in browser
    await launchUrl(webUri, mode: LaunchMode.platformDefault);
  }

  static Future<void> sendSummary({
    required String phoneNumber,
    required String patientName,
    required String summaryText,
    String? doctorName,
  }) async {
    final message = _formatSummary(patientName, summaryText, doctorName);
    final cleaned = _cleanPhone(phoneNumber);
    final encoded = Uri.encodeComponent(message);

    final waUri = Uri.parse('whatsapp://send?phone=$cleaned&text=$encoded');
    if (await canLaunchUrl(waUri)) {
      await launchUrl(waUri, mode: LaunchMode.externalApplication);
      return;
    }

    final webUri = Uri.parse('https://wa.me/$cleaned?text=$encoded');
    if (await canLaunchUrl(webUri)) {
      await launchUrl(webUri, mode: LaunchMode.externalApplication);
      return;
    }

    await launchUrl(webUri, mode: LaunchMode.platformDefault);
  }

  static String _cleanPhone(String phone) {
    String cleaned = phone.replaceAll(RegExp(r'[^\d+]'), '');
    if (cleaned.startsWith('+')) {
      cleaned = cleaned.substring(1);
    }
    if (cleaned.length == 10) {
      cleaned = '91$cleaned';
    } else if (cleaned.length == 12 && cleaned.startsWith('91')) {
      // already has country code
    } else if (cleaned.length > 12) {
      cleaned = '91${cleaned.substring(cleaned.length - 10)}';
    }
    return cleaned;
  }

  static String _formatPrescription(String name, String prescription, String? doctor) {
    final buf = StringBuffer();
    buf.writeln('MedCaller - Prescription');
    buf.writeln();
    buf.writeln('Patient: $name');
    if (doctor != null && doctor.isNotEmpty) {
      buf.writeln('Doctor: $doctor');
    }
    buf.writeln('Date: ${_today()}');
    buf.writeln();
    buf.writeln('Prescription:');
    buf.writeln(prescription);
    buf.writeln();
    buf.writeln('This is a digital prescription from MedCaller.');
    buf.writeln('Please consult your doctor before any changes.');
    return buf.toString();
  }

  static String _formatSummary(String name, String summary, String? doctor) {
    final buf = StringBuffer();
    buf.writeln('MedCaller - Patient Summary');
    buf.writeln();
    buf.writeln('Patient: $name');
    if (doctor != null && doctor.isNotEmpty) {
      buf.writeln('Doctor: $doctor');
    }
    buf.writeln('Date: ${_today()}');
    buf.writeln();
    buf.writeln(summary);
    buf.writeln();
    buf.writeln('Generated by MedCaller AI.');
    return buf.toString();
  }

  static String _today() {
    final now = DateTime.now();
    return '${now.day.toString().padLeft(2, '0')}/${now.month.toString().padLeft(2, '0')}/${now.year}';
  }
}
